# Generated by Django 4.1.6 on 2023-06-03 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hashtag',
        ),
    ]
