# Generated by Django 4.1.6 on 2023-06-04 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_alter_like_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author_comment',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='user',
        ),
    ]
